module.exports = function() { return [
    { phrase: "Googelure.js", cards: 1 },
    { phrase: "140 characters is just enough to explain _____.", cards: 1 },
    { phrase: "_____ all the way down.", cards: 1 },
    { phrase: "_____ as a service.", cards: 1 },
    { phrase: "_____ dooms any project to epic failure.", cards: 1 },
    { phrase: "_____ is a feature, not a bug.", cards: 1 },
    { phrase: "_____ is for closers.", cards: 1 },
    { phrase: "_____ is weaponized privilege.", cards: 1 },
    { phrase: "_____ is webscale.", cards: 1 },
    { phrase: "_____ or it didn't happen.", cards: 1 },
    { phrase: "_____ with one weird trick.", cards: 1 },
    { phrase: "_____, as one does.", cards: 1 },
    { phrase: "_____, for some values of _____.", cards: 2 },
    { phrase: "Ask Me Anything about __________.", cards: 1 },
    { phrase: "Called on account of __________.", cards: 1 },
    { phrase: "Disrupting the established players in __________ via __________.", cards: 2 },
    { phrase: "Doge __________.", cards: 1 },
    { phrase: "Employees must __________ before returning to work.", cards: 1 },
    { phrase: "Enterprise __________ in the cloud.", cards: 1 },
    { phrase: "Enterprise-ready __________.", cards: 1 },
    { phrase: "Epic yak-shave caused by __________.", cards: 1 },
    { phrase: "Facebook has acquired __________ for $10b and __________.", cards: 2 },
    { phrase: "Free as in __________.", cards: 1 },
    { phrase: "Glitter-bombed with __________.", cards: 1 },
    { phrase: "Hi, I'm Troy McClure. You may remember me from such commit messages as __________ and __________.", cards: 2 },
    { phrase: "How even is __________ formed?", cards: 1 },
    { phrase: "I can haz __________.", cards: 1 },
    { phrase: "I don't own any jeans skinny enough to wear to a __________ meetup.", cards: 1 },
    { phrase: "I saw the best minds of my generation __________.", cards: 1 },
    { phrase: "If __________ is the answer, you are asking the wrong question.", cards: 1 },
    { phrase: "If you're __________, you're gonna have a bad time.", cards: 1 },
    { phrase: "Nobody ever got fired for buying __________.", cards: 1 },
    { phrase: "Running Windows in production leads to __________.", cards: 1 },
    { phrase: "The Internet is for cat memes and __________,", cards: 1 },
    { phrase: "\"Our release schedule doesn't have time for _____.\"", cards: 1 },
    { phrase: "The Internet of Things will be controlled by __________.", cards: 1 },
    { phrase: "The only thing necessary for evil to triumph is __________.", cards: 1 },
    { phrase: "Uber is on surge pricing because of __________.", cards: 1 },
    { phrase: "WARN: __________ has been deprecated.", cards: 1 },
    { phrase: "Will merge pull requests for __________.", cards: 1 },
    { phrase: "Zero-day __________.", cards: 1 },
    { phrase: "Time to schedule the postmortem for _____________ .", cards: 1 },
    { phrase: "It worked on my ___________.", cards: 1 },
    { phrase: "___________, the only thing worse than recruiting spam.", cards: 1 },
    { phrase: "___________ - the idiots guide to ___________ and ___________.", cards: 2 },
    { phrase: "Put some ______ on it", cards: 1 },
    { phrase: "Wrap it with the _________ duct tape", cards: 1 },
    { phrase: "But Google is using _________ so we should too!", cards: 1 },
    { phrase: "____________ is the new __________.", cards: 2 },
    { phrase: "Etsy says we should __________ everything.", cards: 1 },
    { phrase: "xkcd.com just made a hilarious comic making fun of ___________.", cards: 1 },
    { phrase: "This isn't going to be all unicorns and _________.", cards: 1 },
    { phrase: "Apple just patented ___________________________.", cards: 1 },
    { phrase: "When I was a kid we didn't have __________.", cards: 1 },
    { phrase: "Root cause of the outage? ________________.", cards: 1 },
    { phrase: "The status console is green, but I can't access _________________.", cards: 1 },
    { phrase: "No route to host: ____________.", cards: 1 },
    { phrase: "DevOps: Now with 100% more ________________!", cards: 1 },
    { phrase: "Main benefits of automation: ____________________ and ___________________.", cards: 2 },
    { phrase: "Chef convergence failed due to _________________.", cards: 1 },
    { phrase: "...and then there was the time I found ___________ on the root partition.", cards: 1 },
    { phrase: "We run production on _____________ and _________________.", cards: 2 },
    { phrase: "Management said it's OK to deploy _________________ at 5pm on Friday ", cards: 1 },
    { phrase: "Did you know that we have ______________ on pager rotation?", cards: 1 },
    { phrase: "\"There was no good solution for _______________, so we built our own.\"", cards: 1 },
    { phrase: "Amazon built a datacenter on the moon to lessen the risk of _________________ causing problems.", cards: 1 },
    { phrase: "In order to improve security, we're upgrading to _______________.", cards: 1 },
    { phrase: "The two pillars of our Continuous Deployment pipeline are ___________________ and ___________________.", cards: 2 },
    { phrase: "I got paged at 3am because of _____________________.", cards: 1 },
    { phrase: "The most stable part of our infrastructure? _____________________", cards: 1 },
    { phrase: "When I told Jez Humble about our ______________, he actually cried.", cards: 1 },
    { phrase: "When I write a book about my experiences, it'll be called \"________________, the good parts\"", cards: 1 },
    { phrase: "Restoring from backups failed due to _________________________.", cards: 1 },
    { phrase: "My two most indispensable tools are ______________ and _______________.", cards: 2 },
    { phrase: "The production datacenter burned down because of __________________.", cards: 1 },
    { phrase: "It turns out that the button labeled \"Don't Push\" actually does ___________.", cards: 1 },
    { phrase: "You should think of your servers like ________ and not like _________.", cards: 2 },
    { phrase: "I find Java to be way too ________.", cards: 1 },
    { phrase: "It's like trying to herd ______.", cards: 1 },
    { phrase: "I ended up having to buy a replacement _______ on eBay.", cards: 1 },
    { phrase: "_______ is more memory than anyone will ever need on a computer.", cards: 1 },
    { phrase: "__________ Driven Development.", cards: 1 },
    { phrase: "RIAA is suing me for downloading ________.", cards: 1 },
    { phrase: "Security? We've got that! We use ______________.", cards: 1 },
    { phrase: "I came up with an awesome regex that converts ____________ to _______________.", cards: 2 },
    { phrase: "When I hooked the 3D printer up to the Internet, it accidentally created _______________.", cards: 1 },
    { phrase: "My next blog post will be about how we used _______________ to create _______________.", cards: 2 },
    { phrase: "So, I was using Wireshark to check network traffic... Did you know we have ________________ in production?", cards: 1 },
    { phrase: "My eyes started bleeding when I opened the editor and saw _______________.", cards: 1 },
    { phrase: "I think maybe I'll leave ______________ off my resumÃ©.", cards: 1 },
    { phrase: "We don't need ______________ - we have _______________ !", cards: 2 },
    { phrase: "Management just told me I need to get certified in ____________________.", cards: 1 },
    { phrase: "Our app is like ___________, but for ________________.", cards: 2 },
    { phrase: "Marketing says we're leaders in the _______________ space, but I think it's more accurate to say we specialize in ___________.", cards: 2 },
    { phrase: "Our greatest achievement in the last year is ________________.", cards: 1 },
    { phrase: "If we make this deadline, Management has promised us ___________________.", cards: 1 },
    { phrase: "Sweet! I just found a Puppet module for ______________!", cards: 1 },
    { phrase: "Last week, I created a Chef recipe for ____________; this week, it's an entire cookbook for ____________. Automation FTW!", cards: 2 },
    { phrase: "We really need to open-source our _________________.", cards: 1 },
    { phrase: "A sales rep just tried to pitch me on ____________; I told them we already have ______________.", cards: 2 },
    { phrase: "Who would have known that ___________ could destroy an entire datacenter?", cards: 1 },
    { phrase: "To secure our next round of funding, Management says we need ________________.", cards: 1 },
    { phrase: "Our production backups are stored using _________________.", cards: 1 },
    { phrase: "We replaced our _________ with ______________", cards: 2 },
    { phrase: "After _________________ came up, the retrospective really went downhill.", cards: 1 },
    { phrase: "You know what our app needs? More ______________, less ____________.", cards: 2 },
    { phrase: "It figures - an article about our ________________ was posted just as we're pivoting to _______________.", cards: 2 },
    { phrase: "In the next planning session, we'll cover __________ and _______________.", cards: 2 },
    { phrase: "Our competitive advantage is our __________________.", cards: 1 },
    { phrase: "Every time someone brings up ______________, I throw up a little in my mouth.", cards: 1 },
    { phrase: "Continuous ___________.", cards: 1 },
    { phrase: "All that we had to do to halve our response times was implement ________________", cards: 1 },
    { phrase: "Our entire app is geared towards providing ________________.", cards: 1 },
    { phrase: "_________-ility", cards: 1 },
    { phrase: "We just achieved _____________s per second!", cards: 1 },
    { phrase: "_______, is that even HA?", cards: 1 },
    { phrase: "My Linkedin Endorsements include __________________.", cards: 1 },
    { phrase: "Users are _______.", cards: 1 },
    { phrase: "Robots are going to make ________ obsolete.", cards: 1 },
    { phrase: "Accidental _________.", cards: 1 },
    { phrase: "An error occurred: E_______", cards: 1 },
    { phrase: "According to the logs, ____________ was initially caused by ___________.", cards: 2 },
    { phrase: "We can just fix that with a little ______.", cards: 1 },
    { phrase: "You can have _____, _____, or _____.  Pick two.", cards: 2 },
    { phrase: "A monad is just a _____ in the category of _____, what's the problem?", cards: 2 },
    { phrase: "Functional programming - if you can't ______ it, ______ it.", cards: 2 },
    { phrase: "On a scale from 1 to 10, this is ___________!", cards: 1 },
    { phrase: "We don't need configuration management, we have ________!", cards: 1 },
    { phrase: "_______, now with _______ support.", cards: 2 },
    { phrase: "RedHat has announced that RHEL 8 will ship with _______.", cards: 1 },
    { phrase: "\"Hey, _______ is down. Can you fix it?\"", cards: 1 },
    { phrase: "I grabbed _____ on my way out the door after our paychecks bounced and management stopped answering their phones.", cards: 1 },
    { phrase: "Did you try ____________ yet?", cards: 1 },
    { phrase: "I was 6 beers in when I got the pager alert that _______was down.", cards: 1 },
    { phrase: "Notice: Building _____________ for ______________", cards: 2 },
    { phrase: "I laughed when they said I'd be on call 24/7 but wouldn't receive a stipend for _____.", cards: 1 },
    { phrase: "If it weren't for __________ we'd all be ___________.", cards: 2 },
    { phrase: "_______, _______ and just a few lines of Perl.", cards: 2 },
    { phrase: "NoSQL is superior to SQL because __________", cards: 1 },
    { phrase: "Script kiddies got into _________ because _________.", cards: 2 },
    { phrase: "______________is better than hadoop because ___________", cards: 2 },
    { phrase: "Rub a little _____________ on it", cards: 1 },
    { phrase: "WAIT, YOU DELETED _______â€½â€½â€½", cards: 1 },
    { phrase: "@______borat", cards: 1 },
    { phrase: "It's not web scale, it's ___________", cards: 1 },
    { phrase: "The tech support hotline told me to ________________", cards: 1 },
    { phrase: "Asynchronous REST API calls are the solution to ______________", cards: 1 },
    { phrase: "Say concurrent threads again and I will ____________ you.", cards: 1 },
    { phrase: "\"Guys, seriously, if we just use ___________ it will solve all our problems with ____________!\"", cards: 2 },
    { phrase: "Facebook changed their profiles today because ______.", cards: 1 },
    { phrase: "github.com/_____/_______", cards: 2 },
    { phrase: "Hello. My name is _______ and I am addicted to _______ .", cards: 2 },
    { phrase: "_________ dependency hell.", cards: 1 },
    { phrase: "That talk outline said it would be about ___________, but it ended up being more like ____________.", cards: 2 },
    { phrase: "I will replace you with a very small ______.", cards: 1 },
    { phrase: "Jordan Sissel hates ______ so much that he created a new opensource project called _________ to work around it.", cards: 2 },
    { phrase: "________ isn't a job title", cards: 1 },
    { phrase: "For the next project we are going to use _________ to solve _________ .", cards: 2 },
    { phrase: "My editor of choice is __________.", cards: 1 },
    { phrase: "_____ it; ship it.", cards: 1 },
    { phrase: "__________-Stack Developer", cards: 1 },
    { phrase: "__________SQL", cards: 1 },
    { phrase: "That's not a hacker, that's my __________!", cards: 1 },
    { phrase: "It has been __ days since the last ______", cards: 2 },
    { phrase: "I've _____ things you people wouldn't ________", cards: 2 },
    { phrase: "The _________ on the server were deleted because _________ .", cards: 2 },
    { phrase: "This week, Aphyr runs _____ through jepsen.", cards: 1 },
    { phrase: "The intern just ran ______ on the load balancer.", cards: 1 },
    { phrase: "I need you to do a _________ with _________ before _________ .", cards: 2 },
    { phrase: "Lambdas are just a lame implementation of _____________.", cards: 1 },
    { phrase: "C-x; C-__________", cards: 1 },
    { phrase: "This users wants _________ because _________ .", cards: 2 },
    { phrase: "_________ should be deprecated in favour of _________ .", cards: 2 },
    { phrase: "_________ mismatch between ________ and ________", cards: 2 },
    { phrase: "I put _________ on the scripts to make it run faster.", cards: 1 },
    { phrase: "Developers do not get access to production machines, because of __________.", cards: 1 },
    { phrase: "Developers need access to production machines because __________.", cards: 1 },
    { phrase: "We run ______ in a cron job every 15 minutes.", cards: 1 },
    { phrase: "The client says it needs more _________ .", cards: 1 },
    { phrase: "We're a __________ as a Service company.", cards: 1 },
    { phrase: "I could hire a __________ to do your job!", cards: 1 },
    { phrase: "My next Velocity talk is called \"____ops\"", cards: 1 },
    { phrase: "The RFO for the global outage was ____ compunded by _____", cards: 2 },
    { phrase: "I was hired to maintain this 20 year old script that runs our critical _______ infrastructure.", cards: 1 },
    { phrase: "Amazon Elastic _________", cards: 1 },
    { phrase: "I know we use __________, but I wrote this critical program in __________.", cards: 2 },
    { phrase: "I'll just have Ops spin up a couple of _______ environments.", cards: 1 },
    { phrase: "I'm writing my next IRC bot with ____________.", cards: 1 },
    { phrase: "SIG____", cards: 1 },
    { phrase: "I cannot wait until someone makes a __________ cluster out of these.", cards: 1 },
    { phrase: "C will finally be displaced by _________", cards: 1 },
    { phrase: "__________.io", cards: 1 },
    { phrase: "We don't need to worry about _________, We're using MongoDB.", cards: 1 },
    { phrase: "Why is ______ better than Hadoop?", cards: 1 },
    { phrase: "FC067: ________________", cards: 1 },
    { phrase: "Oh, the _____ is just a hack to get the ____ to run.", cards: 2 },
    { phrase: "How do I even __________ ?", cards: 1 },
    { phrase: "________ all the things.", cards: 1 },
    { phrase: "ERROR: ______ NOT FOUND", cards: 1 },
    { phrase: "We don't need backups, we've got __________.", cards: 1 },
    { phrase: "Fixing your fathers computer with _________.", cards: 1 },
    { phrase: "it's always a ____________ DNS problem", cards: 1 },
    { phrase: "_______________ with this one weird trick.", cards: 1 },
    { phrase: "________ isn't new, we used to do it in the '70s on mainframes.", cards: 1 },
    { phrase: "Puppet is better than Chef because ______ and __________", cards: 2 },
    { phrase: "How is ______ better than ________ ?", cards: 2 },
    { phrase: "Learn ____ the hard way", cards: 1 },
    { phrase: "vagrant up ________", cards: 1 },
    { phrase: "bollocks up _______", cards: 1 },
    { phrase: "You can fix  __________ with _____________ .", cards: 2 },
    { phrase: "We took the plunge and rewrote _______ in Go", cards: 1 },
    { phrase: "Implementing _____________ should take only 2 lines of code.", cards: 1 },
    { phrase: "I accidentally the entire ___________ is this dangerous?", cards: 1 },
    { phrase: "Good enough for ________ work", cards: 1 },
    { phrase: "Yeah, but can it run _________?", cards: 1 },
    { phrase: "Security through _____.", cards: 1 },
    { phrase: "_________? You can safely ignore that. Usually.", cards: 1 },
    { phrase: "____ isn't cool. You know what's cool? _____", cards: 2 },
    { phrase: "I made a new editor, better than vim and emacs. It's called _______________", cards: 1 },
    { phrase: "640k should be enough for __________.", cards: 1 },
    { phrase: "____________ worked in dev.", cards: 1 },
    { phrase: "You can't fix _________", cards: 1 },
    { phrase: "How hard could it be to port Linux to ___________.", cards: 1 },
    { phrase: "I just finished working on my rocket powered _______.", cards: 1 },
    { phrase: "Richard Stallman will kill you with his teeth for __________.", cards: 1 },
    { phrase: "DB tuning wiith _______.", cards: 1 },
    { phrase: "Can anyone help me get _______ running on Cisco IOS?", cards: 1 },
    { phrase: "Real _________ don't use ______________", cards: 2 },
    { phrase: "________ on XEN", cards: 1 },
    { phrase: "Please bring back __________. You broke my workflow.", cards: 1 },
    { phrase: "I cut-and-pasted this StackOverflow code for my ________.", cards: 1 },
    { phrase: "I'm just finishing up my manifesto on ______________.", cards: 1 },
    { phrase: "r/_____.", cards: 1 },
    { phrase: "We can discuss ______ at the stand-up meeting.", cards: 1 },
    { phrase: "A Beowulf cluster of ____________.", cards: 1 },
    { phrase: "We're demoing _____ for ______ at SXSW.", cards: 2 },
    { phrase: "I aliased ________ to git _________.", cards: 2 },
    { phrase: "10 PRINT \"____________\"; GOTO 10", cards: 1 },
    { phrase: "alt.binaries._________", cards: 1 },
    { phrase: "It is completely dark. You are likely to be eaten by a ____________.", cards: 1 },
    { phrase: "Conway's Game of _______.", cards: 1 },
    { phrase: "Next year I'll start learning ________________", cards: 1 },
    { phrase: "s/______/______/g", cards: 2 },
    { phrase: "________ is the newest gTLD", cards: 1 },
    { phrase: "Works on my ______.", cards: 1 },
    { phrase: "One does not simply _____________", cards: 1 },
    { phrase: "Sorry, you'll need to open a ticket before we can __________.", cards: 1 },
    { phrase: "ln -s ______ _______", cards: 2 },
    { phrase: "_______", cards: 1 },
    { phrase: "__________ is dead.", cards: 1 },
    { phrase: "It compiles __________ to JavaScript.", cards: 1 },
    { phrase: "________-to-butt plugin", cards: 1 },
    { phrase: "Make it _______________.", cards: 1 },
    { phrase: "______coin.", cards: 1 },
    { phrase: "_______ computing", cards: 1 },
    { phrase: "grep _____ | mail ______", cards: 2 },
    { phrase: "______ just got pwned.", cards: 1 },
    { phrase: "It's like __________, but with __________ and list comprehensions.", cards: 2 },
    { phrase: "Software Defined ____________.", cards: 1 },
    { phrase: "I don't have any UNIX Beards in stock, but we do have  _________", cards: 1 },
    { phrase: "Amazon does _______, why can't we?", cards: 1 },
    { phrase: "_________ nagios", cards: 1 },
    { phrase: "I can't believe you're still using __________.", cards: 1 },
    { phrase: "/dev/______: Device is busy", cards: 1 },
    { phrase: "________. You don't exist, go away!", cards: 1 },
    { phrase: "I tried __________. The doctors say I'll never walk again.", cards: 1 },
    { phrase: "git --____________", cards: 1 },
    { phrase: "The _______ Public License.", cards: 1 },
    { phrase: "_____ begins with _____.", cards: 2 },
    { phrase: "Couldn't we use _____?", cards: 1 },
    { phrase: "_________ would be so much better if we rewrote it in Clojure.", cards: 1 },
    { phrase: "So I just found _______ and __________ running in a screen session.", cards: 2 },
    { phrase: "Why is root running ________ under tmux?", cards: 1 },
    { phrase: "Instead of installing _______, what if we just used __________?", cards: 2 },
    { phrase: "I need a webinar like I need _________________.", cards: 1 },
    { phrase: "On the plus side, we finally got rid of ________.", cards: 1 },
    { phrase: "________ thought leader.", cards: 1 },
    { phrase: "It looks like you're trying to __________. Can I help?", cards: 1 },
    { phrase: "bash: command not found: ___________", cards: 1 },
    { phrase: "ETOOMUCH_________", cards: 1 },
    { phrase: "How did ________ ever work?", cards: 1 },
    { phrase: "Whoops, I thought that method was supposed to ________ the __________.", cards: 2 },
    { phrase: "I thought you said __________ was secure?", cards: 1 },
    { phrase: "git: You are in detached ________ state.", cards: 1 },
    { phrase: "Why don't we just fork __________ ?", cards: 1 },
    { phrase: "Network dropped connection because of ___________.", cards: 1 },
    { phrase: "We turned off ________ and everything magically got better.", cards: 1 },
    { phrase: "I found a Samba share full of ___________", cards: 1 },
    { phrase: "_________. What could go wrong?", cards: 1 },
    { phrase: "Install ______", cards: 1 },
    { phrase: "I installed ________ by accident.", cards: 1 },
    { phrase: "Read-eval-__________-loop.", cards: 1 },
    { phrase: "We should try it with an actual _________.", cards: 1 },
    { phrase: "Is __________ something we need to optimize for?", cards: 1 },
    { phrase: "Hack __________ into redis.", cards: 1 },
    { phrase: "_______ Considered Harmful", cards: 1 },
    { phrase: "never ________ before a demonstration", cards: 1 },
    { phrase: "The ___________ is used when the CPU is on fire", cards: 1 },
    { phrase: "modperl can be used to implement _______________", cards: 1 },
    { phrase: "__________ runs Ruby as root", cards: 1 },
    { phrase: "Larry Wall trained as missonary then _________________", cards: 1 },
    { phrase: "Listening to the fans in the server farm leads to _________________", cards: 1 },
    { phrase: "_________ and _____________ are rumoured to be working on a python module for a helicam", cards: 2 },
    { phrase: "A lot of disk space is needed for __________", cards: 1 },
    { phrase: "automagical ___________", cards: 1 },
    { phrase: "Whoever made the unscheduled change to production on Friday will be forced to use _____.", cards: 1 },
    { phrase: "Install _____", cards: 1 },
    { phrase: "Never question the ____", cards: 1 },
    { phrase: "I can't wait until we no longer use _____", cards: 1 },
    { phrase: "I bet if we switch to ______ it will just work", cards: 1 },
    { phrase: "_____ has just discovered _____.  We're doomed.", cards: 2 },
    { phrase: "A neckbeard made of ______________.", cards: 1 },
    { phrase: "False alarm, it was just __________ running ____________.", cards: 2 },
    { phrase: "_____ running on a rack of _____.", cards: 2 },
    { phrase: "No, _____ being hopelessly broken is NOT an emergency.", cards: 1 },
    { phrase: "Our new startup is the _____ for ______.", cards: 2 },
    { phrase: "_____ make me a sandwich", cards: 1 },
    { phrase: "_____ over IP", cards: 1 },
    { phrase: "I AM working, I'm waiting for the _____ run to finish.", cards: 1 },
    { phrase: "The first rule of _____ is: You do not talk about _____.", cards: 2 },
    { phrase: "Google Analytics says 100% of my website visitors are _________", cards: 1 },
    { phrase: "_______will never get job in Microsoft", cards: 1 },
    { phrase: "We can _____ just like Netflix", cards: 1 },
    { phrase: "_____ is how I resolve all merge conflicts.", cards: 1 },
    { phrase: "Why does someone keep re-implementing system utilities in _____?", cards: 1 },
    { phrase: "Remember when you told me to tell you when you were acting ______ and ______? ---you're doing it now. ", cards: 2 },
    { phrase: "Our only hope at recovering the data is _____________", cards: 1 },
    { phrase: "_____: the gift that keeps on giving.", cards: 1 },
    { phrase: "________ has been killed with fire.  My work is done here.", cards: 1 },
    { phrase: "Problem exists between Keyboard and _____", cards: 1 },
    { phrase: "100% government funded _____!", cards: 1 },
    { phrase: "The _____ certification program.", cards: 1 },
    { phrase: "_____? I'd hit that.", cards: 1 },
    { phrase: "_____ makes robots moves", cards: 1 },
    { phrase: "I just finished writing an API for _____.", cards: 1 },
    { phrase: "_____.  Failed to cache catalog.", cards: 1 },
    { phrase: "Everytime you allocate you have to _______ when you're done", cards: 1 },
    { phrase: "Sorry, I'm all out of _____-fu.", cards: 1 },
    { phrase: "90% of everything is __________.", cards: 1 },
    { phrase: "Given enough _____, all bugs are _____.", cards: 2 },
    { phrase: "_________ never use on git", cards: 1 },
    { phrase: "The first 90% of development is _____. The second 90% is _____.", cards: 2 },
    { phrase: "When you logged in there, did you see a _______ that said ________", cards: 2 },
    { phrase: "Purely numeric hostname and not a _______ -----rejecting!", cards: 1 },
    { phrase: "I'm pretty sure ________ isn't thread safe", cards: 1 },
    { phrase: "We don't have to worry about CAP Theorem because of _____.", cards: 1 },
    { phrase: "I don't always test my code, but when I do I do it in _____.", cards: 1 },
    { phrase: "Those who don't understand _____ are condemned to reinvent it, poorly", cards: 1 },
    { phrase: "Of course culture is important to us, that's why we have _____.", cards: 1 },
    { phrase: "The NSA is really interested in our latest project: _____.", cards: 1 },
    { phrase: "Just change the ________, it'll be fine. ", cards: 1 },
    { phrase: "Yeah, you need to modprobe ________ to get it to recognize the ________", cards: 2 },
    { phrase: "Oh, we're devops! We have ______ in the office, but only the DBA can touch it.", cards: 1 },
    { phrase: "We're spending 20% of this sprint doing ________.", cards: 1 },
    { phrase: "_________ found a new OpenSSL vulernability people are calling _______.", cards: 2 },
    { phrase: "Management has changed all our job titles to _________.", cards: 1 },
    { phrase: "while true; do ____; done", cards: 1 },
    { phrase: "The consultant we hired is certain that _____________ will drastically increase the performance of ___________", cards: 2 },
    { phrase: "Could you just push this update for _________?  It should be a no-op.", cards: 1 },
    { phrase: "If we're all going to get fired, let's get fired for __________.", cards: 1 },
    { phrase: "We can't pay you, but we can offer _____ in compensation.", cards: 1 },
    { phrase: "A soiled napkin with the contents of ______ scribbled on it", cards: 1 },
    { phrase: "Who thought that _______ was a good idea?", cards: 1 },
    { phrase: "It's not the recommended configuration to use __________ with ____________ but it's in production right now.", cards: 2 },
    { phrase: "We wrote our own build tool based on _____", cards: 1 },
    { phrase: "I've received a Microsoft MVP Award for _____", cards: 1 },
    { phrase: "We rewrote _____________ in _____________", cards: 2 },
    { phrase: "The ticket to install _____?  I deletegated it.", cards: 1 },
    { phrase: "Artisanally crafted ___.", cards: 1 },
    { phrase: "The backups are fine, but the restore process is ____________", cards: 1 },
    { phrase: "The ___ that ops provides developers.", cards: 1 },
    { phrase: "Move ___ and break things.", cards: 1 },
    { phrase: "_______: ci or not ci?", cards: 1 },
    { phrase: "I opened the server cabinet and it was full of _____.", cards: 1 },
    { phrase: "Crossing _____ could lead to total protonic reversal.", cards: 1 },
    { phrase: "I______your stupid issue!", cards: 1 },
    { phrase: "Nine circles of ___ hell.", cards: 1 },
    { phrase: "I asked the contractor for _____ and they delivered _____.", cards: 2 },
    { phrase: "I'd like _____, _____, and a pony.", cards: 2 },
    { phrase: "Only the Enterprise Edition(tm) has _____.", cards: 1 },
    { phrase: "The trouble with kids these days is ____________", cards: 1 },
    { phrase: "_____ for the win!", cards: 1 },
    { phrase: "______ is the new __________", cards: 2 },
    { phrase: "With _____, you write once, run nowhere.", cards: 1 },
    { phrase: "_____ discontinued support for the Linux version.", cards: 1 },
    { phrase: "A manager told me I couldn't remove our dependency on _____, but I got around it with _____.", cards: 2 },
    { phrase: "_____ implements every single standard for _____.  Poorly.", cards: 2 },
    { phrase: "Just think of the Internet as _____.", cards: 1 },
    { phrase: "Would you like _____ with that?", cards: 1 },
    { phrase: "_____? We've got that.", cards: 1 },
    { phrase: "It took over 40 hours to document _____. ", cards: 1 },
    { phrase: "npm install ________.", cards: 1 },
    { phrase: "Circular imports import _____. ", cards: 1 },
    { phrase: "_____ is why the jDBA thought it might be time to go to #mysql on freenode", cards: 1 },
    { phrase: "_____ is the only reason the jDBA survived typing rm -rf /", cards: 1 },
    { phrase: "End-to-end _____.", cards: 1 },
    { phrase: "It's like _____ on _____.", cards: 2 },
    { phrase: "________ will help you remember to sanitze your database inputs.", cards: 1 },
    { phrase: "_____ took EBS down again today.", cards: 1 },
    { phrase: "_____, the final solution.", cards: 1 },
    { phrase: "We're running _____ in production?!", cards: 1 },
    { phrase: "_____ has root access.", cards: 1 },
    { phrase: "We don't have enough package managers said _____", cards: 1 },
    { phrase: "_____ is more reliable than ______", cards: 2 },
    { phrase: "_____ ate all my memory", cards: 1 },
    { phrase: "It's easy! Just run _____", cards: 1 },
    { phrase: "I assure you _____ is secure!", cards: 1 },
    { phrase: "Our backup policy is _____", cards: 1 }
]; }