module.exports = function() { return [
    "Angular js",
    "A former MENSA member",
    "Being acquired by Oracle",
    "Brogrammers",
    "Command-line magic",
    "Continuous integration",
    "Copypasta",
    "The Cult of Mac",
    "Degraded performance in some AWS availability zones",
    "Developers",
    "DevOps",
    "Eating sushi with Andrew Clay Shafer",
    "Git",
    "Golang",
    "Growth hacking",
    "Hacker News",
    "Larry Ellison",
    "Leaky abstractions",
    "LinkedIn",
    "Meritocracy",
    "MongoDB",
    "Node.js",
    "NPM",
    "Pareto Inefficient Nash Equilibriums",
    "Posting on Etsy's codeascraft blog",
    "Python",
    "Python datetime module",
    "RecruiterFail",
    "Ruby",
    "Running out of IPv4 addresses",
    "Sysadmins",
    "The Stanford of Canada",
    "Thought leadership",
    "Twitter",
    "Unicode errors",
    "Unknown source in your stack trace",
    "Waiting for console.aws.amazon.com",
    "Women in tech",
    "Yet another package manager",
    "Our Release Engineer",
    "DevOps Days",
    "OpenSSL",
    "Heartbleed",
    "The NSA",
    "O'Reilly",
    "Edward Snowden",
    "Digital Ocean",
    "Magic Spray",
    "Web scale",
    "Functional programming",
    "Stack trace generator",
    "Patent",
    "NoSQL",
    "Windows XP",
    "Perl 6",
    "COTS Shareware",
    "2400 baud modem",
    "A squirrel with a taste for fiber",
    "Zombie processes",
    "CAP Theorem",
    "Snowflake server",
    "A Cisco router with a flaky chip",
    "NullPointerException: null",
    "Apache 1.2 running as root",
    "More buzzwords than you can shake a scrum at",
    "A GitHub Outage",
    "VisualBasic DLLs",
    "A JAR full of spaghetti",
    "An epic caffeine bender",
    "A WSDL from 2003",
    "The Sales & Marketing department",
    "Business logic in PowerPoint slides",
    "/var/log symlinked to /dev/null",
    "Hypervisors running hypervisors running hypervisors",
    "An angry badger with an electromagnet on its back",
    "A shared root password",
    "Private keys in /var/www",
    "Parsing HTML with regex",
    "A 3.5\" floppy disk",
    "An untested restore process",
    "A cron job that reboots the server every 5 minutes",
    "Apache Zookeeper on a 286",
    "Sadness as a Service",
    "Cloud-based business strategy",
    "Cloud 2.0",
    "The next Y2K",
    "An army of chaos monkeys, all carrying flamethrowers",
    "A CORBA service written in Ada which communicates using JSONx",
    "A home-rolled systemd replacement",
    "A custom kernel with Frontpage Extensions installed",
    "A mobile web 2.0 RIA",
    "Agony-Driven Development",
    "Catastrophic Failure as a Service",
    "10,000 Nagios alerts per second",
    "A global write lock",
    "75-tier architecture",
    "Hand-crafted artisan x86 assembly code",
    "The world's only fully-functional ROFLcopter",
    "A proof that P=NP written in BASIC",
    "An Exchange email loop",
    "A Volker-Craig terminal",
    "A self-aware PHP script",
    "A 500-megabyte UDP packet",
    "The last remaining Multics server on Earth",
    "A Null-modem cable",
    "A turducken made entirely of bash scripts",
    "Write-only code",
    "PagerDuty configured with a random number generator",
    "Netscape Navigator 3.2 support",
    "3 hour standups",
    "A PiÃ±ata full of error messages",
    "Mutation of immutable data",
    "Maven downloading the entire internet",
    "Continuous Disintegration",
    "IE6",
    "Scrum Master",
    "Magic Smoke",
    "done done",
    "Tech Debt Day",
    "Log Shipping",
    "uucp",
    "4chan Party Van",
    "Adderall",
    "Tcl",
    "NoOps",
    ":(){ :|:&};:",
    "Too Big Data",
    "Accidentally the entire data center",
    "freebasing caffeine",
    "Fat fingered",
    "Half open TCP connections",
    "Steve Balmer wielding a battleaxe",
    "A 50k line Bash script that's achieved self awareness",
    "Gigadevops",
    "Enterprise Grade Bash scripts",
    "Agile",
    "A pink sombrero and a fifth of tequila",
    "A simple 15 level Hiera hierarachy",
    "lolscale.",
    "CouchDB",
    "GeoCouchDB",
    "High Availability",
    "Map-Reduce",
    "Web Scale?",
    "Erlang",
    "a non-ironic BSOD",
    "ntpdate",
    "Systemd",
    "12 factor application",
    "Fail early, fail often",
    "Regex",
    "A violation of the most basic engineering principles.",
    "The BOFH",
    "A water buffalo",
    "a routing loop",
    "a queue with no consumers",
    "Bitcoin mining",
    "A firewall full of holes",
    "An uncontrollable deluge of emails",
    "I heard about it on hacker news",
    "Ycombinator",
    "a jailbroken iPad",
    "Vagrant",
    "Nokogiri Gem",
    "Docker",
    "a \"MRW\" animated gif",
    "$HOME/.gem",
    "a posting on Craigslist \"internet engineers\" jobs forum",
    "ssh in a for loop",
    "a cold cup of coffee",
    "Destroying your tools with your tools",
    "UTF-9",
    "a dozen vendor t-shirts",
    "unlimited data plan",
    "UTF-7",
    "out-of-band access",
    "rm -rf /",
    "kill -9",
    "a series of tiny shellscripts",
    "Dogecoin",
    "Kernel panic",
    "Hugops!",
    "Lolcats",
    "Culture",
    "Percussive maintenance",
    "IE 7 Support",
    "Hangops",
    "Unix philosophy",
    "Trying to install MongoDB on AIX 3",
    "A server rack full of crushed dreams",
    "Node.js",
    "Silos",
    "Elastic Load Balancers",
    "RFC1178",
    "Full-stack developer",
    "Andrew Clay Shaffer",
    "Jordan Sissel",
    "A new printer.",
    "A potato",
    "Office Space",
    "Git Blame",
    "Developers! Developers! Developers! Developers!",
    "Your account",
    "Single stepping through the kernel",
    "De-linting source code",
    "Significant whitespace",
    "Smart quotes",
    "A series of tubes",
    "secret sauce",
    "# What is this used for?",
    "# FIXME: For now, just don't validate",
    "ASAP",
    "Nagios",
    "The Goddamn CDN",
    "Authentication and authorization",
    "A cluster of applications on a cluster of servers",
    "Beating the server into submission with your bare hands.",
    "Read-only Fridays",
    "r/sysadmin",
    "Distributed Computing",
    "Sprint Planning",
    "Merge Conflicts",
    "# we *LIE* about what happened and return a \"success\"",
    "Unplugging a server and waiting to see who complains",
    "THE MAGMA PEOPLE ARE WAITING FOR OUR MISTAKES.",
    "a tiny ounce of knowledge",
    "Too big to fail",
    "NoQA Movement",
    "A few instances",
    "operations hipster",
    "Cowboy developer",
    "cubism farm",
    "HipChat",
    "An IRC bot written entirely in sed",
    "works for me",
    "a torrent of Torrenters torrenting",
    "COBOL",
    "in b4 FIRST",
    "Donald Knuth",
    "Rebooting All The Things",
    "Running Openstack in Production",
    "the Berkshelf way",
    "DNS",
    "SIGHUP",
    "Animated GIF",
    "Heartbleed",
    "PC LOAD LETTER",
    "Automate",
    "Delightful",
    "Cache",
    "Proxy",
    "an online book seller",
    "Dust Bunnies",
    "Pete Cheslock",
    "Networking",
    "A sad log with a mustache",
    "Blue Screen Of Death",
    "iso 8601",
    "Daniel J. Bernstein",
    "Linus Torvalds",
    "Broadcom chipset",
    "Moe",
    "That XKCD comic about sysadmins",
    "iso 8859",
    "RFC 1149",
    "A pimply faced youth with nothing to lose",
    "Theo de Raadt yelling at newbs",
    "Hate driven development",
    "Lotus123",
    "/dev/null as a service",
    "Hackathons",
    "GNU/Linux",
    "ZeroVM",
    "Stringing cloudtobutt.pl into postfix.",
    "ZeroMQ over SSH",
    "SQLite",
    "LevelDB",
    "Leap second bug",
    "continuous deployment",
    "Tor",
    "bash",
    "numactl",
    "zsh",
    "Vegan friendly init scripts.",
    "Committing from the bar.",
    "Servers that follow daylight savings time.",
    "Rolling Grubhub into the build failed script.",
    "command line options",
    "Temporary hotfixes",
    "jsLinux",
    "SIGKILL",
    "Your private browsing history",
    "Wearing protection during peer programing.",
    "top",
    "Arguing over the internet.",
    "year 2038",
    "dd",
    "pdisk",
    "rsync",
    "CFLAGS",
    "cowsay",
    "profanity in the git log",
    "Gentoo",
    "The CEO",
    "Ping Pong",
    "Dennis Ritchie",
    "PAM Happy Hour",
    "Complex systems usually operate in failure mode.",
    "FAT32",
    "winsock",
    "fork() on Windows",
    "runlists",
    "sudo",
    "echo shell_exec(\"sudo ./smbkill \".escapeshellcmd($_GET['kill']).\" 2>&1\");",
    "kill -9 -1",
    "curl 4chan | sudo sh",
    "cassandra",
    "HTML9 Responsive Boilerstrap JS",
    "Neckbeards",
    "A Certified SCRUM Master",
    "Bus error",
    "git reset --hard origin/master",
    "Forcing push to master",
    "Paxos",
    "LogFiles\W3SVC1",
    "A German installation of Windows NT4",
    "curl | sh -c",
    "OpenLDAP",
    "Spot Instances",
    "Those ksh scripts",
    "/cgi-bin/php5",
    "A $60 QNAP and some positive thinking",
    "raspberryPI",
    "Windows ME",
    "@echo off",
    "Active Directory",
    "conflict minerals",
    "continuous incineration",
    "The gentle sound of weeping drifting from the server room",
    "eventual consistency",
    "Microsoft Azure",
    "Pinging the broadcast address",
    "That moment when you realize CTRL-Z cannot save you",
    "127.0.0.1",
    "Ethernet",
    "IPv6",
    "Re-writing deployment scripts at 2 AM",
    "Piping /var/log/messages to Twitter",
    "Bare metal",
    "A pseudorandom number generator",
    "An outage window",
    "Sentinel System Driver",
    "fpm",
    "catastrophic cancellation",
    "termcap",
    "f00d",
    "one giant SPOF",
    "Richard Stallman's Neckbeard",
    "phpMyAdmin",
    "Righteous Anger",
    "Crowdsourced Architecture",
    "/etc/hosts",
    "CEOs with root access",
    "Automagic Metaprogramming",
    "Re-implementing TCP over UDP",
    "Rewriting bash scripts as CMD batch jobs",
    "#define BEGIN  {",
    "Microsoft Access over a WAN",
    "git submodules",
    "Haskell",
    "Functional Reactive",
    "Paxos",
    "memegen",
    "Flynn",
    "eventual persistence",
    "Jenkins",
    "Bingo Balls",
    "Mechanically Recovered Turkey",
    "ChatOps",
    "Scala",
    "WONTFIX",
    "Trello board",
    "Big ball of mud",
    "Friday afternoon deployment",
    "YoloDB",
    "Piping random scripts from the internet into bash",
    "post-mortems",
    "Github selfies",
    "Production deployments that depend on GitHub",
    "RFC 2324",
    "Your code featured on The Daily WTF.",
    "optimistic transactions",
    "Webscale",
    "Cats",
    "Ponies",
    "Your Mum",
    "Picking the best color to paint your bike shed",
    "Server cages",
    "Copy-on-write",
    "deduplication",
    "LART",
    "BOFH",
    "Program Management",
    "Product Managers",
    "The Ballmer Peak",
    "0xDEADBEEF",
    "A coked-up tech recruiter",
    "A contractor that tells you it was a real learning experience",
    "RTFM",
    "A 1996 Java applet",
    "A virtual machine running a virtual machine until it brings on the Singularity",
    "Ops doing dev = technical debt",
    "#And right here, we'd like a miracle.",
    "Sparkly Devops Princess",
    "Patrick Debois",
    "git merge --force",
    "A series of tubes",
    ":(){:|:&};:",
    "The library that imports all other libraries",
    "An entirely commented out file",
    "A constructor for RandomThing",
    "Circular imports",
    "A pull request with a winking smiley ;)",
    "Syntactic sugar coma",
    "Former employees who still have admin access to live production servers",
    "The ib_logfiles",
    "The mysql client",
    "Paul Graham",
    "The much neglected IPv5",
    "cron jobs that edit cron jobs",
    "snail scale",
    "Testing positive for mongonucleosis",
    "PEBKAC",
    "ReiserFS",
    "/dev/null",
    "little Bobby Tables",
    "solar flares",
    "global warming",
    "Short Stroking",
    "Reticulating Splines",
    "RAID 3 SSD cluster",
    "Re-implementing TCP over TCP",
    "Mixed endianness",
    "OAuth",
    "traceroute",
    "rockstar",
    "packet loss",
    "smokeping",
    "losing the root password",
    "Works on my machine!",
    "malloc",
    "buffer overflow",
    "StackOverflow is offline?!",
    "server logs",
    "Penetration test",
    "Deploying on a Friday afternoon",
    "Quipu",
    "too many authorization failures",
    "two single quotes",
    "kremvax",
    "the unix epoch",
    "0 day exploits",
    "tribal knowledge",
    "puppet",
    "RHEL4",
    "DevOps Reactions",
    "syntax error",
    "killall -9",
    "pre caffeine typos",
    "banana pi",
    "RAID 0",
    "PIP",
    "PyPy",
    "Synergy",
    "dev",
    "java",
    "geometric distances",
    "Indian Ocean",
    "rm -rf /",
    "hunter2",
    "GCHQ",
    "NSA FOIA request",
    "wat",
    "kanban",
    "Halt and Catch Fire"
]; }